config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :users
  post '/access', to: 'access_control#sign_in'
  get '/access', to: 'access_control#log_out'
  get '/attend/:id', to: 'access_control#attend'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  def self.attending?(user, event)
    user.attendances.where(event_id: event.id)
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :creator, class_name: 'User'
  scope :past_events, -> { where('date < ?', Date.today) }
  scope :upcoming_events, -> { where('date >= ?', Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances
  has_many :events, through: :attendances
  has_many :own_events, foreign_key: 'creator_id', class_name: 'Event'
end

app/controllers/access_control_controller.rb
class AccessControlController < ApplicationController
  def sign_in
    valid_user = User.where(name: params[:user][:name])
    if valid_user.empty?
      redirect_to users_path
    else
      session[:username] = params[:user][:name]
      session[:email] = params[:user][:email]
      session[:user_id] = valid_user[0].id

      redirect_to events_path
    end
  end

  def log_out
    session.destroy
    redirect_to users_path
  end

  def attend
    attend = Attendance.new
    attend.user_id = session[:user_id]
    attend.event_id = params[:id]
    attend.save
    redirect_to events_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :check_user_login
  # GET /events
  # GET /events.json
  def index
    @past = Event.all.past_events
    @future = Event.all.upcoming_events
    @user = User.find(session[:user_id])
  end

  # GET /events/1
  # GET /events/1.json
  def show; end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    logger.info("\n\n##########PARAMS: #{event_params}\n\n")
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:title, :body, :date, :location, :creator_id)
  end

  def check_user_login
    redirect_to users_path if session[:username].nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    # @users = User.all
    @user = User.new
    render 'sign_in'
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sign_in
    if User.where(name: params[:user][:name]).empty?
      redirect_to users_path
    else
      session[:username] = params[:user][:name]
      session[:email] = params[:user][:email]
      redirect_to events_path
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/access_control_helper.rb
module AccessControlHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def attending(user, event)
    link_to 'Attend', "/attend/#{event.id}" if Attendance.attending?(user, event).empty?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, "Name of the event" %><br><br>
    <%= form.text_field :title %>
  </div>
  <br>
  <div class="field">
    <%= form.label :body, "Description" %><br><br>
    <%= form.text_area :body %>
  </div>
  <br>
  <div class="field">
    <%= form.label :date %><br><br>
    <%= form.date_select :date %>
  </div>
  <br>
  <div class="field">
    <%= form.label :location %><br><br>
    <%= form.text_field :location %>
  </div>
  <br>
  <%= form.hidden_field :creator_id, :value =>session[:user_id] %> 
  <div class="actions">

    <%= form.submit  %><br>

  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>
<div class="event-welcome">
  <span>
    Welcome: <b><%= session[:username] %></b> 
  </span>
   <a class="my-account" href= <%= "/users/#{session[:user_id]}" %> >My Account</a>
</div>

<div class="table-container">
  <div class="table-1">
    <h1 class="table-head">Upcoming Events</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Date</th>
          <th>Location</th>
          <th>Creator</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @future.each do |event| %>
            <tr class="table-row">
              <td><%= event.title %></td>
              <td><%= event.body %></td>
              <td><%= event.date %></td>
              <td><%= event.location %></td>
              <td><%= event.creator.name %></td>
              <td><span class="link"><%= link_to 'Show', event %></span></td>
              <td><span class="link"><%= attending(@user,event) %></span></td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="table-2">
    <h1 class="table-head">Past Events</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Date</th>
          <th>Location</th>
          <th>Creator</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @past.each do |event| %>
            <tr>
              <td><%= event.title %></td>
              <td><%= event.body %></td>
              <td><%= event.date %></td>
              <td><%= event.location %></td>
              <td ><%= event.creator.name %></td>
              <td ><span class="link"><%= link_to 'Show', event %></span></td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>
<div class="center-new-event">
<div class="new-event">
  <b><%= link_to 'Create New Event', new_event_path, class: "event-text" %></b>
</div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>
<br>
<%= link_to 'Back', events_path  %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Event Info</h2>
<p>
  <strong>Name:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.body %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>
<br>
<br>
<p>
  <h2>Attendees:</h2>
  <% @event.attendances.each do | e | %>
  	<p> <%= e.user.name %></p>
  <% end %>
</p>


<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Associations</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main-container">
      <nav>
        <span class="title">Event Manager</span>
        <a href="/access" class="log-out">Log Out</a>
      </nav>
      <div class="sub-container">
        
          <%= yield %>
        
      </div>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br> <br>
    <%= form.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= form.label :email %><br><br>
    <%= form.text_field :email %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
  <br>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

  <h2 class="table-head padding">My created events</h2>
  <% @user.own_events.each do |e| %>
    <p><b>Event:</b> <%= e.title %> <b>Date:</b> <%= e.date %></p>
  <% end %>

  <h2 class="table-head padding">My Past Events</h2>

  <% @user.events.past_events.each do |e| %>
    <p><b>Event:</b> <%= e.title %> <b>Date:</b> <%= e.date %></p>
  <% end %>


  <h2 class="table-head padding">My Upcoming Events</h2>
  <% @user.events.upcoming_events.each do |e| %>
    <p><b>Event:</b> <%= e.title %> <b>Date:</b> <%= e.date %></p>
  <% end %>

<%= link_to 'Back', events_path %>

app/views/users/sign_in.html.erb
<p id="notice"><%= notice %></p>

<h1>Sign in to see the Events</h1>
<%= form_for(@user,  url: "/access", method: :post) do |form| %>
  <div class="field">
    <%= form.label :name, "Enter your name" %><br><br>
    <%= form.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= form.label :email, "Enter your email" %><br><br>
    <%= form.text_field :email %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit 'Sign In'%>
  </div>
<% end %>


<br>

New To the page? <b><%= link_to 'Create a New User', new_user_path %></b>